name: Auto Earthquake Data Update (Every 6 Hours)

# Run every Sunday 02:00 UTC and manually
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo with write permissions (using PAT) and full history for rebase
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Ensure data folder exists
      - name: Ensure data folder
        run: mkdir -p data

      # 5️⃣ Fetch latest earthquake CSV
      - name: Fetch earthquake data
        run: python src/fetch_data.py

      # 6️⃣ Commit and push CSV only, set temporary git identity
      - name: Commit and push updates
        run: |
         git config user.name "github-actions[bot]"
         git config user.email "github-actions[bot]@users.noreply.github.com"
         git add data/earthquakes.csv
         git commit -m "Weekly auto-update of earthquake data" || echo "No changes to commit"
         git push --force origin HEAD:main
