name: Weekly Earthquake Data Update

on:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data folder exists
        run: mkdir -p data

      - name: Fetch latest earthquake data
        run: python src/fetch_data.py

      - name: Commit and push updates
        run: |
          git add data/earthquakes.csv
          git commit -m "Weekly auto-update of earthquake data" || echo "No changes to commit"
          git push
