
name: Weekly Earthquake Data Update

# Run every Sunday at 02:00 UTC, or manually
on:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data folder exists
        run: mkdir -p data

      - name: Fetch latest earthquake data
        run: python src/fetch_data.py

      - name: Generate HTML map
        run: python src/generate_map.py

      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/earthquakes.csv data/earthquakes_map.html
          git commit -m "Weekly auto-update of earthquake data"
          git push
        continue-on-error: true  # avoids failure if no changes
